// <auto-generated />
using System;
using DeliveryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliveryAPI.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDriverId = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 22, 34, 35, 536, DateTimeKind.Utc).AddTicks(3774),
                            CustomerName = "Jan Kowalski",
                            DeliveryAddress = "ul. Warszawska 15, Warszawa",
                            OrderNumber = "ORD-001",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AssignedDriverId = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 22, 34, 35, 536, DateTimeKind.Utc).AddTicks(4199),
                            CustomerName = "Anna Nowak",
                            DeliveryAddress = "ul. Krakowska 22, Kraków",
                            OrderNumber = "ORD-002",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            AssignedDriverId = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 22, 34, 35, 536, DateTimeKind.Utc).AddTicks(4203),
                            CustomerName = "Piotr Wiśniewski",
                            DeliveryAddress = "ul. Gdańska 8, Gdańsk",
                            OrderNumber = "ORD-003",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("DeliveryAPI.Models.DeliveryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("DeliveryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryId = 1,
                            IsDelivered = false,
                            Price = 25.99m,
                            ProductName = "Pizza Margherita",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            DeliveryId = 1,
                            IsDelivered = false,
                            Price = 5.99m,
                            ProductName = "Coca Cola 0.5L",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            DeliveryId = 2,
                            IsDelivered = false,
                            Price = 18.99m,
                            ProductName = "Burger Wołowy",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            DeliveryId = 2,
                            IsDelivered = false,
                            Price = 8.99m,
                            ProductName = "Frytki duże",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            DeliveryId = 2,
                            IsDelivered = false,
                            Price = 5.99m,
                            ProductName = "Sprite 0.5L",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            DeliveryId = 3,
                            IsDelivered = false,
                            Price = 45.99m,
                            ProductName = "Sushi Set",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            DeliveryId = 3,
                            IsDelivered = false,
                            Price = 3.99m,
                            ProductName = "Woda mineralna 0.5L",
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("DeliveryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 22, 34, 35, 250, DateTimeKind.Utc).AddTicks(577),
                            Email = "admin@delivery.com",
                            PasswordHash = "$2a$11$xphDl.Rp0y3k6wX1YAq.ZeTvaL.zk1CJtEBshpF.AgDdryKMQChcK",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 22, 34, 35, 534, DateTimeKind.Utc).AddTicks(6646),
                            Email = "driver1@delivery.com",
                            PasswordHash = "$2a$11$ctRme1sjxy/j57rmtPm6MuU3RqrYQcoXTelTGw8d1P5bPkipO.Seu",
                            Role = "Driver",
                            Username = "driver1"
                        });
                });

            modelBuilder.Entity("DeliveryAPI.Models.Delivery", b =>
                {
                    b.HasOne("DeliveryAPI.Models.User", "AssignedDriver")
                        .WithMany("Deliveries")
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedDriver");
                });

            modelBuilder.Entity("DeliveryAPI.Models.DeliveryItem", b =>
                {
                    b.HasOne("DeliveryAPI.Models.Delivery", "Delivery")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("DeliveryAPI.Models.Delivery", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DeliveryAPI.Models.User", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
